const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const L = require('./learning.js');
const context = {window:{}};
vm.runInNewContext(fs.readFileSync('data.js','utf8'),context);
const data=context.window.EXAM_DATA, ids=data.questions.map(q=>q.id);
assert.equal(ids.length,216);assert.equal(new Set(ids).size,216);
assert.equal(data.questions.filter(q=>q.exam==='vt22').length,25);
assert.equal(data.questions.filter(q=>q.exam==='dk1').length,40);
assert.equal(data.exams.filter(e=>e.primary).length,2);
assert.equal(data.questions.filter(q=>data.exams.find(e=>e.id===q.exam)?.primary).length,65);
for(const y of [2023,2024])assert.equal(new Set(data.questions.filter(q=>q.year===y).map(q=>q.original)).size,20);
for(const q of data.questions){assert(q.answer.length>20);assert(q.prompt.length>15);assert(data.exams.some(e=>e.id===q.exam));for(const src of q.sources)assert(data.sources[src]?.url.startsWith('https://'));if(q.exam==='vt22')assert(q.teacher?.length>0);if(q.exam==='dk1'){assert(q.teacher?.length>0);assert.equal(q.teacherSource,'Tentamen VT 22 Rättningsmall-1.doc');assert(q.sourcePage>=3&&q.sourcePage<=17);}for(const im of q.images||[]){assert(fs.existsSync(im.src));assert(im.width>0&&im.height>0);}}
const quick=data.questions.filter(q=>q.exam==='quickquiz');
assert.equal(quick.length,45);assert.equal(quick.filter(q=>q.exception).length,31);
for(const section of ['1','2','3','4','4a','5','6','7'])assert(quick.some(q=>q.tblSection===section));
for(const q of quick){assert.equal(q.choices.length,3);assert.equal(new Set(q.choices).size,3);assert(!q.teacher);assert.equal(q.reviewed,'2026-09-16');assert(L.isCorrect(q,{choice:0}));assert(!L.isCorrect(q,{choice:1}));}
const quick2=data.questions.filter(q=>q.exam==='quickquiz2');assert.equal(quick2.length,45);
assert.equal(quick2.filter(q=>q.manual==='O').length,23);assert.equal(quick2.filter(q=>q.manual==='A').length,22);
for(const q of quick2){assert.equal(q.choices.length,3);assert.equal(new Set(q.choices).size,3);assert(q.manualTitle);assert(q.manualPage>=2&&q.manualPage<=(q.manual==='O'?11:14));assert.equal(q.reviewed,'2026-09-18');assert(L.isCorrect(q,{choice:0}));assert(!L.isCorrect(q,{choice:2}));}
const images=[...new Set(data.questions.flatMap(q=>(q.images||[]).map(i=>i.src)))];assert.equal(images.length,20);
const sw=fs.readFileSync('sw.js','utf8');for(const path of images)assert(sw.includes('./'+path));
const multi=data.questions.find(q=>q.id==='dk1-18');assert.equal(multi.choices.length,6);assert.deepEqual(Array.from(multi.correct),[1,2,4]);
assert(L.isCorrect(multi,{selected:[4,1,2]}));
for(const selected of [[],[1],[1,2],[1,2,4,5],[1,2,2],[0,3,5]])assert(!L.isCorrect(multi,{selected}));
assert(!L.isCorrect(multi,{choice:1}));assert(L.isCorrect({choices:['A','B']},{choice:0}));
assert(!L.isCorrect({choices:['A','B']},{choice:1}));
const now=1000000,day=86400000;
let review;
for(const days of [1,3,7,14,30,30]){review=L.schedule(review,'known',now);assert.equal(review.due,now+days*day)}
review=L.schedule(review,'hard',now);assert.equal(review.streak,0);assert.equal(review.due,now+day);
assert.equal(L.schedule(review,'known',now).due,now+day);
const legacy={ratings:{[ids[0]]:'hard'},drafts:{[ids[0]]:'Mitt äldre svar'},stars:[ids[0]],session:{ids:[ids[0]],index:0,answers:{},mode:'Test'}};
const restored=L.normalize(legacy,ids);assert.equal(restored.session.answers[ids[0]].draft,'Mitt äldre svar');assert.equal(restored.ratings[ids[0]],'hard');
assert.equal(L.normalize({...legacy,session:{ids:['missing'],index:0}},ids).session,null);
assert.equal(L.normalize({...legacy,session:{ids:[ids[0]],index:-1}},ids).session,null);
assert.throws(()=>L.normalize({},ids));
const roundtrip=L.normalize(JSON.parse(JSON.stringify({...restored,reviews:{[ids[0]]:review}})),ids);
assert.deepEqual(roundtrip.reviews[ids[0]],review);assert.equal(roundtrip.session.answers[ids[0]].draft,'Mitt äldre svar');
const multiSaved={...restored,session:{ids:['dk1-18'],index:0,answers:{'dk1-18':{selected:[1,2,4],checked:[0,1],revealed:true}},mode:'Dk1'}};
const multiRestored=L.normalize(JSON.parse(JSON.stringify(multiSaved)),ids);
assert.deepEqual(multiRestored.session.answers['dk1-18'].selected,[1,2,4]);assert(L.isCorrect(multi,multiRestored.session.answers['dk1-18']));assert.deepEqual(multiRestored.session.answers['dk1-18'].checked,[0,1]);
const oldId=data.questions.find(q=>q.year===2023).id;
const oldProgress=L.normalize({ratings:{[oldId]:'known'},drafts:{[oldId]:'Tidigare Växjösvar'},stars:[oldId],session:{ids:[oldId],index:0,mode:'2023',answers:{}}},ids);
assert.equal(oldProgress.ratings[oldId],'known');assert.equal(oldProgress.session.answers[oldId].draft,'Tidigare Växjösvar');
const app=fs.readFileSync('app.js','utf8');
const selectText=app.slice(app.indexOf('function quickSelection('),app.indexOf('function quiz()'));
const selectContext={QUICK:quick,state:{ratings:{'quick-01':'hard'}},dueQuestions:()=>[]};
vm.runInNewContext(selectText,selectContext);
for(const [topic,n] of [['all',45],['exceptions',31],['tbl',19],['hard',1],['due',0],['Saluvagn',2]])assert.equal(selectContext.quickSelection(topic).length,n);
assert(selectContext.quickSelection('tbl').every(q=>q.tblSection));
assert(selectContext.quickSelection('exceptions').every(q=>q.exception));
const select2Text=app.slice(app.indexOf('function quick2Selection('),app.indexOf('function quiz2()'));
const select2Context={QUICK2:quick2,state:{ratings:{'quick2-01':'hard'}},dueQuestions:()=>[]};vm.runInNewContext(select2Text,select2Context);
for(const [topic,n] of [['all',45],['O',23],['A',22],['hard',1],['due',0]])assert.equal(select2Context.quick2Selection(topic).length,n);
const functionText=app.slice(app.indexOf('function requiredLicense('),app.indexOf('function calc()'));
const calcContext={};vm.runInNewContext(functionText,calcContext);
for(const [c,t,result] of [[3500,750,'B'],[2500,1000,'B'],[2500,1001,'B96'],[3500,751,'BE'],[3000,1250,'B96'],[3000,1251,'BE'],[3500,3500,'BE'],[0,750,null],[3501,750,null],[3000,750.5,null]])assert.equal(calcContext.requiredLicense(c,t),result);
for(const f of ['index.html','app.js','data.js','sw.js','learning.js'])assert(!fs.readFileSync(f,'utf8').includes('\ufffd'));
assert(fs.readFileSync('index.html','utf8').includes('data-version="'+data.version+'"'));
assert(fs.readFileSync('sw.js','utf8').includes('trafiktenta-'+data.version));
console.log('PASS: 216 exercises (65 primary + 61 legacy + 45 quick quiz + 45 quickquiz2), all TBL sections and 31 exception questions, teacher/source labels, 20 images and offline assets, exact multi-answer scoring, saved selections/checklists, legacy migration, repetition intervals, invalid imports, licence boundaries, version/encoding.');
